// angular-frontend/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, CommonModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  isUserSignedIn = false;
}

<header class="border-b flex items-center justify-center bg-white">
  <div class="container flex h-16 items-center justify-between px-4 md:px-6">
    <!-- Logo -->
    <span class="flex items-center gap-2">
      <span class="text-xl font-bold text-blue-600">MediBook</span>
    </span>

    <!-- Navigation (non-clickable) -->
    <nav class="hidden md:flex gap-6">
      <span class="text-sm font-medium hover:text-blue-600 cursor-default"
        >Features</span
      >
      <span class="text-sm font-medium hover:text-blue-600 cursor-default"
        >About</span
      >
      <span class="text-sm font-medium hover:text-blue-600 cursor-default"
        >Contact</span
      >
    </nav>

    <!-- Auth Buttons -->
    <div class="flex items-center gap-4">
      <!-- Signed-out state -->
      <ng-container *ngIf="!isUserSignedIn">
        <a
          routerLink="/auth"
          class="hidden md:inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 cursor-default"
        >
          Sign In
        </a>
        <span
          class="inline-flex items-center px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700 cursor-default"
        >
          Get Started
        </span>
      </ng-container>

      <!-- Signed-in state -->
      <ng-container *ngIf="isUserSignedIn">
        <span
          class="hidden md:inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-white bg-red-400 hover:bg-red-500 cursor-default"
        >
          Sign Out
        </span>
      </ng-container>
    </div>
  </div>
</header>

<router-outlet></router-outlet>

// vue-frontend/src/App.vue
<template>
  <div>
    <header class="border-b flex items-center justify-center bg-white">
      <div
        class="container flex h-16 items-center justify-between px-4 md:px-6"
      >
        <router-link to="/" class="flex items-center gap-2">
          <span class="text-xl font-bold text-primary">MediBook</span>
        </router-link>

        <nav class="hidden md:flex gap-6">
          <router-link
            to="#features"
            class="text-sm font-medium hover:text-primary"
          >
            Features
          </router-link>
          <router-link to="#" class="text-sm font-medium hover:text-primary">
            About
          </router-link>
          <router-link to="#" class="text-sm font-medium hover:text-primary">
            Contact
          </router-link>
        </nav>

        <div class="flex items-center gap-4">
          <template v-if="!store.user">
            <router-link to="/auth">
              <Button variant="outline" size="sm" class="hidden md:flex">
                Sign In
              </Button>
            </router-link>
            <router-link to="/auth">
              <Button size="sm">Get Started</Button>
            </router-link>
          </template>
          <template v-else>
            <Button
              variant="outline"
              size="sm"
              class="hidden md:flex bg-red-400 text-white"
              @click="store.removeUser"
            >
              Sign out
            </Button>
          </template>
        </div>
      </div>
    </header>

    <router-view></router-view>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useUserStore } from "@/stores/user"; // Import the Pinia store
import { Button } from "@/components/ui/button"; // Adjust path to your Button component

export default defineComponent({
  name: "App",
  components: {
    Button,
  },
  setup() {
    const store = useUserStore(); // Initialize the store

    return {
      store, // Expose the entire store to the template
    };
  },
});
</script>

<style scoped>
/* TailwindCSS handles styling */
</style>
