// react-frontend/src/pages/Dashboard.tsx
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { format } from "date-fns";
import { cn } from "@/lib/utils";
import {
  CalendarIcon,
  Clock,
  Plus,
  User,
  CalendarPlus2Icon as CalendarIcon2,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";
import { useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import { Appointment, AppointmentStatus, UserRole } from "@/types";
import { createAppointment, getAppointments } from "@/api/appointmentservice";

// Mock data for doctors
const doctors = [
  { id: 1, name: "Dr. Sarah Johnson", specialty: "Cardiologist" },
  { id: 6, name: "Dr. Michael Chen", specialty: "Dermatologist" },
  { id: 7, name: "Dr. Emily Rodriguez", specialty: "General Practitioner" },
  { id: 8, name: "Dr. David Wilson", specialty: "Neurologist" },
  { id: 11, name: "Dr. Lisa Thompson", specialty: "Pediatrician" },
];

export function Dashboard() {
  const { user } = useSelector((state: RootState) => state.user);
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [date, setDate] = useState<Date | undefined>(new Date());
  const [selectedAppointment, setSelectedAppointment] =
    useState<Appointment | null>(null);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [isNewAppointmentOpen, setIsNewAppointmentOpen] = useState(false);

  // New appointment form state
  const [newAppointment, setNewAppointment] = useState({
    doctor: "",
    date: new Date(),
    time: "09:00",
    duration: 30,
    reason: "",
  });

  useEffect(() => {
    const fetchUserAppointments = async () => {
      const res = await getAppointments();
      console.log(res);
      setAppointments(res.data);
    };
    fetchUserAppointments();
  }, []);

  if (!user) {
    // alert("You need to be logged in to access this page.");
    return (
      <div className="min-h-screen bg-gradient-to-b from-white to-blue-50 flex justify-center items-center ">
        <main className="container px-4 py-6 md:py-10 ">
          <h1 className="text-3xl font-bold tracking-tight text-center">
            You need to be logged in to access this page.
          </h1>
        </main>
      </div>
    );
  }

  // Filter appointments by selected date
  // const filteredAppointments = appointments.filter((appointment) =>
  //   date ? appointment.date.toDateString() === date.toDateString() : true
  // );

  const handleAppointmentClick = (appointment: Appointment) => {
    setSelectedAppointment(appointment);
    setIsDetailsOpen(true);
  };

  const handleStatusChange = () => {
    if (selectedAppointment) {
      selectedAppointment.status =
        selectedAppointment.status === AppointmentStatus.SCHEDULED
          ? AppointmentStatus.COMPLETED
          : AppointmentStatus.SCHEDULED;
      setIsDetailsOpen(false);
    }
  };

  const handleScheduleAppointment = async () => {
    // Schedule new appointment
    console.log(newAppointment);
    try {
      const res = await createAppointment({
        date: newAppointment.date,
        doctorId: Number(newAppointment.doctor),
        duration: newAppointment.duration,
        reason: newAppointment.reason,
        time: newAppointment.time,
      });
      console.log(res);
      setAppointments([...appointments, res.data]);
    } catch (error) {
      console.error(error);
    }

    setIsNewAppointmentOpen(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-blue-50 flex justify-center ">
      <main className="container px-4 py-6 md:py-10">
        {/* Top section */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">
              {user.role === UserRole.PATIENT
                ? "My Appointments"
                : "Patient Appointments"}
            </h1>
            <p className="text-muted-foreground">
              {user.role === "patient"
                ? "Manage your upcoming medical appointments"
                : "View and manage your scheduled patient appointments"}
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <Popover>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  className="w-full sm:w-auto justify-start text-left font-normal"
                >
                  <CalendarIcon className="mr-2 h-4 w-4" />
                  {date ? format(date, "PPP") : "Pick a date"}
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-auto p-0">
                <Calendar
                  mode="single"
                  selected={date}
                  onSelect={setDate}
                  initialFocus
                />
              </PopoverContent>
            </Popover>

            {user.role === "patient" && (
              <Button onClick={() => setIsNewAppointmentOpen(true)}>
                <Plus className="mr-2 h-4 w-4" />
                New Appointment
              </Button>
            )}
          </div>
        </div>

        {appointments.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <CalendarIcon2 className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-medium">No appointments found</h3>
            <p className="text-muted-foreground mt-1">
              {user.role === "patient"
                ? "You don't have any appointments scheduled for this date."
                : "You don't have any patient appointments scheduled for this date."}
            </p>
            {user.role === "patient" && (
              <Button
                variant="outline"
                className="mt-4"
                onClick={() => setIsNewAppointmentOpen(true)}
              >
                Schedule an appointment
              </Button>
            )}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {appointments.map((appointment) => (
              <Card
                key={appointment.id}
                className={cn(
                  "cursor-pointer transition-all hover:shadow-md",
                  appointment.status === "Completed"
                    ? "border-l-4 border-l-green-500"
                    : "border-l-4 border-l-primary"
                )}
                onClick={() => handleAppointmentClick(appointment)}
              >
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-start">
                    <CardTitle>
                      {user.role === "patient"
                        ? appointment.doctor.name
                        : appointment.patient.name}
                    </CardTitle>
                    <div
                      className={cn(
                        "px-2 py-1 rounded-full text-xs font-medium",
                        appointment.status === "Completed"
                          ? "bg-green-100 text-green-800"
                          : "bg-blue-100 text-blue-800"
                      )}
                    >
                      {appointment.status}
                    </div>
                  </div>
                  <CardDescription>{appointment.reason}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center text-sm mb-1">
                    <CalendarIcon2 className="mr-2 h-4 w-4 text-muted-foreground" />
                    {format(appointment.date, "EEEE, MMMM d, yyyy")}
                  </div>
                  <div className="flex items-center text-sm">
                    <Clock className="mr-2 h-4 w-4 text-muted-foreground" />
                    {format(appointment.date, "h:mm a")}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* Appointment Details Modal */}
        <Dialog open={isDetailsOpen} onOpenChange={setIsDetailsOpen}>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>Appointment Details</DialogTitle>
              <DialogDescription>
                {user.role === "patient"
                  ? "View or modify your appointment details"
                  : "View your patient's appointment details"}
              </DialogDescription>
            </DialogHeader>

            {selectedAppointment && (
              <div className="space-y-4 py-2">
                <div className="flex items-start gap-4">
                  <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                    <User className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-medium">
                      {user.role === "patient"
                        ? selectedAppointment.doctor.name
                        : selectedAppointment.patient.name}
                    </h3>
                  </div>
                </div>

                <div className="grid gap-2">
                  <div className="flex items-center">
                    <CalendarIcon2 className="mr-2 h-4 w-4 text-muted-foreground" />
                    <span>
                      {format(selectedAppointment.date, "EEEE, MMMM d, yyyy")}
                    </span>
                  </div>
                  <div className="flex items-center">
                    <Clock className="mr-2 h-4 w-4 text-muted-foreground" />
                    <span>{format(selectedAppointment.date, "h:mm a")}</span>
                  </div>
                  <div className="flex items-center">
                    {selectedAppointment.status === "Completed" ? (
                      <CheckCircle2 className="mr-2 h-4 w-4 text-green-500" />
                    ) : (
                      <AlertCircle className="mr-2 h-4 w-4 text-primary" />
                    )}
                    <span>{selectedAppointment.status}</span>
                  </div>
                </div>

                <div>
                  <h4 className="text-sm font-medium mb-1">
                    {user.role === "patient" ? "Notes" : "Reason for Visit"}
                  </h4>
                  <p className="text-sm text-muted-foreground">
                    {selectedAppointment.reason}
                  </p>
                </div>

                {user.role === "patient" &&
                  selectedAppointment.status === "Scheduled" && (
                    <div>
                      <h4 className="text-sm font-medium mb-1">Reschedule</h4>
                      <div className="flex gap-2">
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button
                              variant="outline"
                              size="sm"
                              className="w-[150px] justify-start text-left font-normal"
                            >
                              <CalendarIcon className="mr-2 h-4 w-4" />
                              {format(selectedAppointment.date, "PPP")}
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <Calendar
                              mode="single"
                              selected={new Date(selectedAppointment.date)}
                              onSelect={(date) => {
                                if (date) {
                                  const newDate = new Date(
                                    selectedAppointment.date
                                  );
                                  newDate.setFullYear(date.getFullYear());
                                  newDate.setMonth(date.getMonth());
                                  newDate.setDate(date.getDate());
                                  selectedAppointment.date =
                                    newDate.toDateString();
                                }
                              }}
                              initialFocus
                            />
                          </PopoverContent>
                        </Popover>

                        <Select
                          defaultValue={format(
                            selectedAppointment.date,
                            "HH:mm"
                          )}
                          onValueChange={(value) => {
                            const [hours, minutes] = value
                              .split(":")
                              .map(Number);
                            const newDate = new Date(selectedAppointment.date);
                            newDate.setHours(hours);
                            newDate.setMinutes(minutes);
                            selectedAppointment.date = newDate.toDateString();
                          }}
                        >
                          <SelectTrigger className="w-[110px]">
                            <SelectValue placeholder="Select time" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="09:00">9:00 AM</SelectItem>
                            <SelectItem value="10:00">10:00 AM</SelectItem>
                            <SelectItem value="11:00">11:00 AM</SelectItem>
                            <SelectItem value="13:00">1:00 PM</SelectItem>
                            <SelectItem value="14:00">2:00 PM</SelectItem>
                            <SelectItem value="15:00">3:00 PM</SelectItem>
                            <SelectItem value="16:00">4:00 PM</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  )}
              </div>
            )}

            <DialogFooter className="flex flex-col-reverse sm:flex-row sm:justify-between sm:space-x-2">
              <Button variant="outline" onClick={() => setIsDetailsOpen(false)}>
                Cancel
              </Button>

              {user.role === "patient" &&
                selectedAppointment?.status === "Scheduled" && (
                  <Button onClick={() => setIsDetailsOpen(false)}>
                    Update Appointment
                  </Button>
                )}

              {user.role === "doctor" && (
                <Button
                  onClick={handleStatusChange}
                  variant={
                    selectedAppointment?.status === "Completed"
                      ? "outline"
                      : "default"
                  }
                >
                  {selectedAppointment?.status === "Completed"
                    ? "Mark as Scheduled"
                    : "Mark as Completed"}
                </Button>
              )}
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* New Appointment Modal */}
        <Dialog
          open={isNewAppointmentOpen}
          onOpenChange={setIsNewAppointmentOpen}
        >
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>Schedule New Appointment</DialogTitle>
              <DialogDescription>
                Fill in the details to book your appointment with a doctor.
              </DialogDescription>
            </DialogHeader>

            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <Label htmlFor="doctor">Select Doctor</Label>
                <Select
                  value={newAppointment.doctor}
                  onValueChange={(value) =>
                    setNewAppointment({ ...newAppointment, doctor: value })
                  }
                >
                  <SelectTrigger id="doctor">
                    <SelectValue placeholder="Select a doctor" />
                  </SelectTrigger>
                  <SelectContent>
                    {doctors.map((doctor) => (
                      <SelectItem key={doctor.id} value={doctor.id.toString()}>
                        {doctor.name} - {doctor.specialty}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="date">Date</Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        id="date"
                        variant="outline"
                        className="w-full justify-start text-left font-normal"
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {newAppointment.date
                          ? format(newAppointment.date, "PPP")
                          : "Pick a date"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={newAppointment.date}
                        onSelect={(date) =>
                          date && setNewAppointment({ ...newAppointment, date })
                        }
                        initialFocus
                        disabled={(date) =>
                          date < new Date() ||
                          date.getDay() === 0 ||
                          date.getDay() === 6
                        }
                      />
                    </PopoverContent>
                  </Popover>
                </div>

                <div className="grid gap-2">
                  <Label htmlFor="time">Time</Label>
                  <Select
                    value={newAppointment.time}
                    onValueChange={(time) =>
                      setNewAppointment({ ...newAppointment, time })
                    }
                  >
                    <SelectTrigger id="time">
                      <SelectValue placeholder="Select time" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="09:00">9:00 AM</SelectItem>
                      <SelectItem value="10:00">10:00 AM</SelectItem>
                      <SelectItem value="11:00">11:00 AM</SelectItem>
                      <SelectItem value="13:00">1:00 PM</SelectItem>
                      <SelectItem value="14:00">2:00 PM</SelectItem>
                      <SelectItem value="15:00">3:00 PM</SelectItem>
                      <SelectItem value="16:00">4:00 PM</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="notes">Reason</Label>
                <Input
                  id="notes"
                  placeholder="Any specific concerns or information for the doctor"
                  value={newAppointment.reason}
                  onChange={(e) =>
                    setNewAppointment({
                      ...newAppointment,
                      reason: e.target.value,
                    })
                  }
                />
              </div>
            </div>

            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setIsNewAppointmentOpen(false)}
              >
                Cancel
              </Button>
              <Button onClick={() => handleScheduleAppointment()}>
                Schedule Appointment
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </main>
    </div>
  );
}

// angular-frontend/src/app/dashboard/dashboard.component.ts
import { Component, inject } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { Appointment, AppointmentStatus } from '../store/appointment.state';
import * as AppointmentActions from '../store/appointment.actions';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import { CommonModule } from '@angular/common';
import { AppState, User } from '../store/user.state';
import { format } from 'date-fns';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
})
export class DashboardComponent {
  private store = inject(Store<AppState>);
  private fb = inject(FormBuilder);

  user$: Observable<User | null> = this.store.select(
    (state) => state.user.user
  );
  appointments$: Observable<Appointment[]> = this.store.select(
    (state) => state.appointments?.appointments || []
  );
  loading$: Observable<boolean> = this.store.select(
    (state) => state.appointments.loading
  );
  error$: Observable<string | null> = this.store.select(
    (state) => state.appointments.error
  );

  date: Date = new Date();
  selectedAppointment: Appointment | null = null;
  isDetailsOpen = false;
  isNewAppointmentOpen = false;

  newAppointmentForm: FormGroup = this.fb.group({
    doctor: ['', Validators.required],
    date: [new Date(), Validators.required],
    time: ['09:00', Validators.required],
    duration: [30, Validators.required],
    reason: ['', Validators.required],
  });

  doctors = [
    { id: 1, name: 'Dr. Sarah Johnson', specialty: 'Cardiologist' },
    { id: 6, name: 'Dr. Michael Chen', specialty: 'Dermatologist' },
    { id: 7, name: 'Dr. Emily Rodriguez', specialty: 'General Practitioner' },
    { id: 8, name: 'Dr. David Wilson', specialty: 'Neurologist' },
    { id: 11, name: 'Dr. Lisa Thompson', specialty: 'Pediatrician' },
  ];

  constructor() {
    this.store.dispatch(AppointmentActions.loadAppointments());
  }

  formatDate(date: string | Date): string {
    return format(new Date(date), 'PPP');
  }

  formatTime(date: string | Date): string {
    return format(new Date(date), 'h:mm a');
  }

  handleAppointmentClick(appointment: Appointment) {
    this.selectedAppointment = { ...appointment };
    this.isDetailsOpen = true;
  }

  handleStatusChange() {
    if (this.selectedAppointment) {
      this.selectedAppointment.status =
        this.selectedAppointment.status === AppointmentStatus.SCHEDULED
          ? AppointmentStatus.COMPLETED
          : AppointmentStatus.SCHEDULED;
      this.isDetailsOpen = false;
    }
  }

  handleScheduleAppointment() {
    if (this.newAppointmentForm.valid) {
      const { doctor, date, time, duration, reason } =
        this.newAppointmentForm.value;
      const isoDate = new Date(date);
      const [hours, minutes] = time.split(':');
      isoDate.setHours(+hours, +minutes);

      this.store.dispatch(
        AppointmentActions.createAppointment({
          doctorId: +doctor,
          date: isoDate.toISOString(),
          time,
          duration,
          reason,
        })
      );
      this.isNewAppointmentOpen = false;
      this.newAppointmentForm.reset({
        doctor: '',
        date: new Date(),
        time: '09:00',
        duration: 30,
        reason: '',
      });
    }
  }
}

<div class="min-h-screen flex flex-col bg-gradient-to-b from-white to-blue-50">
  <main class="container px-4 py-6 md:py-10 flex-1">
    <ng-container *ngIf="user$ | async as user; else notLoggedIn">
      <!-- Top Section -->
      <div
        class="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4"
      >
        <div>
          <h1 class="text-3xl font-bold tracking-tight">
            {{
              user.role === "patient"
                ? "My Appointments"
                : "Patient Appointments"
            }}
          </h1>
          <p class="text-gray-500">
            {{
              user.role === "patient"
                ? "Manage your upcoming medical appointments"
                : "View and manage your scheduled patient appointments"
            }}
          </p>
        </div>
        <div class="flex flex-col sm:flex-row gap-4">
          <!-- Date Picker (Simplified) -->
          <input
            #dateInput
            type="date"
            [value]="date | date : 'yyyy-MM-dd'"
            (change)="date = dateInput.valueAsDate!"
            class="border border-gray-300 rounded-md p-2"
          />
          <button
            *ngIf="user.role === 'patient'"
            (click)="isNewAppointmentOpen = true"
            class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700"
          >
            <svg
              class="inline mr-2 h-4 w-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 4v16m8-8H4"
              ></path>
            </svg>
            New Appointment
          </button>
        </div>
      </div>

      <!-- Appointments List -->
      <ng-container *ngIf="appointments$ | async as appointments">
        <div
          *ngIf="appointments.length > 0; else noAppointments"
          class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          <div
            *ngFor="let appointment of appointments$ | async"
            (click)="handleAppointmentClick(appointment)"
            class="cursor-pointer border-l-4 p-4 bg-white rounded-md shadow-md hover:shadow-lg"
            [ngClass]="{
              'border-l-green-500': appointment.status === 'Completed',
              'border-l-blue-600': appointment.status !== 'Completed'
            }"
          >
            <div class="flex justify-between items-start">
              <h3 class="font-bold">
                {{
                  user.role === "patient"
                    ? appointment.doctor.name
                    : appointment.patient.name
                }}
              </h3>
              <span
                class="px-2 py-1 rounded-full text-xs font-medium"
                [ngClass]="{
                  'bg-green-100 text-green-800':
                    appointment.status === 'Completed',
                  'bg-blue-100 text-blue-800':
                    appointment.status !== 'Completed'
                }"
              >
                {{ appointment.status }}
              </span>
            </div>
            <p class="text-gray-500">{{ appointment.reason }}</p>
            <div class="flex items-center text-sm mt-2">
              <svg
                class="mr-2 h-4 w-4 text-gray-500"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                ></path>
              </svg>
              {{ formatDate(appointment.date) }}
            </div>
            <div class="flex items-center text-sm mt-1">
              <svg
                class="mr-2 h-4 w-4 text-gray-500"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                ></path>
              </svg>
              {{ formatTime(appointment.date) }}
            </div>
          </div>
        </div>
      </ng-container>

      <!-- No Appointments -->
      <ng-template #noAppointments>
        <div
          class="flex flex-col items-center justify-center py-12 text-center"
        >
          <svg
            class="h-12 w-12 text-gray-500 mb-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
            ></path>
          </svg>
          <h3 class="text-lg font-medium">No appointments found</h3>
          <p class="text-gray-500 mt-1">
            {{
              user.role === "patient"
                ? "You don’t have any appointments scheduled for this date."
                : "You don’t have any patient appointments scheduled for this date."
            }}
          </p>
          <button
            *ngIf="user.role === 'patient'"
            (click)="isNewAppointmentOpen = true"
            class="mt-4 border border-gray-300 px-4 py-2 rounded-md hover:bg-gray-50"
          >
            Schedule an appointment
          </button>
        </div>
      </ng-template>

      <!-- Appointment Details Modal -->
      <div
        *ngIf="isDetailsOpen"
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center"
      >
        <div class="bg-white rounded-md p-6 w-full max-w-md">
          <h2 class="text-xl font-bold">Appointment Details</h2>
          <p class="text-gray-500">View or modify your appointment details</p>
          <div class="space-y-4 mt-4">
            <div class="flex items-start gap-4">
              <div
                class="h-10 w-10 rounded-full bg-blue-100 flex items-center justify-center"
              >
                <svg
                  class="h-5 w-5 text-blue-600"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                  ></path>
                </svg>
              </div>
              <h3 class="font-medium">
                {{
                  user.role === "patient"
                    ? selectedAppointment?.doctor?.name
                    : selectedAppointment?.patient?.name
                }}
              </h3>
            </div>
            <div class="space-y-2">
              <div class="flex items-center">
                <svg
                  class="mr-2 h-4 w-4 text-gray-500"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                  ></path>
                </svg>
                {{ formatDate(selectedAppointment?.date || "") }}
              </div>
              <div class="flex items-center">
                <svg
                  class="mr-2 h-4 w-4 text-gray-500"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                  ></path>
                </svg>
                {{ formatTime(selectedAppointment?.date || "") }}
              </div>
              <div class="flex items-center">
                <svg
                  class="mr-2 h-4 w-4"
                  [ngClass]="{
                    'text-green-500':
                      selectedAppointment?.status === 'Completed',
                    'text-blue-600': selectedAppointment?.status !== 'Completed'
                  }"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    [attr.d]="
                      selectedAppointment?.status === 'Completed'
                        ? 'M5 13l4 4L19 7'
                        : 'M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z'
                    "
                  ></path>
                </svg>
                {{ selectedAppointment?.status }}
              </div>
            </div>
            <div>
              <h4 class="text-sm font-medium mb-1">
                {{ user.role === "patient" ? "Notes" : "Reason for Visit" }}
              </h4>
              <p class="text-sm text-gray-500">
                {{ selectedAppointment?.reason }}
              </p>
            </div>
          </div>
          <div class="flex justify-between mt-6">
            <button
              (click)="isDetailsOpen = false"
              class="border border-gray-300 px-4 py-2 rounded-md hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              *ngIf="user.role === 'doctor'"
              (click)="handleStatusChange()"
              class="px-4 py-2 rounded-md"
              [ngClass]="{
                'bg-blue-600 text-white hover:bg-blue-700':
                  selectedAppointment?.status !== 'Completed',
                'border border-gray-300 hover:bg-gray-50':
                  selectedAppointment?.status === 'Completed'
              }"
            >
              {{
                selectedAppointment?.status === "Completed"
                  ? "Mark as Scheduled"
                  : "Mark as Completed"
              }}
            </button>
          </div>
        </div>
      </div>

      <!-- New Appointment Modal -->
      <div
        *ngIf="isNewAppointmentOpen"
        class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center"
      >
        <div class="bg-white rounded-md p-6 w-full max-w-md">
          <h2 class="text-xl font-bold">Schedule New Appointment</h2>
          <p class="text-gray-500">
            Fill in the details to book your appointment.
          </p>
          <form
            [formGroup]="newAppointmentForm"
            (ngSubmit)="handleScheduleAppointment()"
            class="space-y-4 mt-4"
          >
            <div class="space-y-2">
              <label for="doctor" class="block text-sm font-medium"
                >Select Doctor</label
              >
              <select
                id="doctor"
                formControlName="doctor"
                class="w-full border border-gray-300 rounded-md p-2"
              >
                <option value="">Select a doctor</option>
                <option *ngFor="let doctor of doctors" [value]="doctor.id">
                  {{ doctor.name }} - {{ doctor.specialty }}
                </option>
              </select>
            </div>
            <div class="grid grid-cols-2 gap-4">
              <div class="space-y-2">
                <label for="date" class="block text-sm font-medium">Date</label>
                <input
                  id="date"
                  type="date"
                  formControlName="date"
                  class="w-full border border-gray-300 rounded-md p-2"
                />
              </div>
              <div class="space-y-2">
                <label for="time" class="block text-sm font-medium">Time</label>
                <select
                  id="time"
                  formControlName="time"
                  class="w-full border border-gray-300 rounded-md p-2"
                >
                  <option value="09:00">9:00 AM</option>
                  <option value="10:00">10:00 AM</option>
                  <option value="11:00">11:00 AM</option>
                  <option value="13:00">1:00 PM</option>
                  <option value="14:00">2:00 PM</option>
                  <option value="15:00">3:00 PM</option>
                  <option value="16:00">4:00 PM</option>
                </select>
              </div>
            </div>
            <div class="space-y-2">
              <label for="reason" class="block text-sm font-medium"
                >Reason</label
              >
              <input
                id="reason"
                formControlName="reason"
                placeholder="Any specific concerns"
                class="w-full border border-gray-300 rounded-md p-2"
              />
            </div>
            <div class="flex justify-end gap-2">
              <button
                type="button"
                (click)="isNewAppointmentOpen = false"
                class="border border-gray-300 px-4 py-2 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700"
              >
                Schedule Appointment
              </button>
            </div>
          </form>
        </div>
      </div>
    </ng-container>

    <!-- Not Logged In -->
    <ng-template #notLoggedIn>
      <div class="flex justify-center items-center h-full">
        <h1 class="text-3xl font-bold tracking-tight text-center">
          You need to be logged in to access this page.
        </h1>
      </div>
    </ng-template>
  </main>
</div>
